import { defineConfig } from 'tsup';

export default defineConfig([
  {
    // Shared base is dropped so the `./*` exports resolve to `dist/<name>.js`.
    entry: [
      'src/index.ts',
      ...[
        'agent',
        'artifact',
        'attachments',
        'audio-player',
        'canvas',
        'chain-of-thought',
        'checkpoint',
        'code-block',
        'commit',
        'confirmation',
        'connection',
        'context',
        'controls',
        'conversation',
        'edge',
        'environment-variables',
        'file-tree',
        'image',
        'inline-citation',
        'jsx-preview',
        'message',
        'mic-selector',
        'model-selector',
        'node',
        'open-in-chat',
        'package-info',
        'panel',
        'persona',
        'plan',
        'prompt-input',
        'question',
        'queue',
        'reasoning',
        'sandbox',
        'schema-display',
        'shimmer',
        'snippet',
        'sources',
        'speech-input',
        'stack-trace',
        'suggestion',
        'task',
        'terminal',
        'test-results',
        'tool',
        'toolbar',
        'transcription',
        'voice-selector',
        'web-preview',
      ].map(name => `src/${name}.tsx`),
    ],
    outDir: 'dist',
    format: ['cjs', 'esm'],
    // Disable code splitting; the CJS build emits an ESM passthrough index
    // (bare `export *`) when entries re-export other entries, which breaks
    // Node's CommonJS resolution.
    splitting: false,
    external: [
      'react',
      'react-dom',
      'lucide-react',
      '@ai-toolkit/shadcn-ui',
      'ai-toolkit',
      'clsx',
      'tailwind-merge',
      'class-variance-authority',
      'radix-ui',
      'cmdk',
      'embla-carousel-react',
      '@radix-ui/react-use-controllable-state',
      '@rive-app/react-webgl2',
      'use-stick-to-bottom',
      'motion',
      'ansi-to-react',
      'react-jsx-parser',
      'shiki',
      '@xyflow/react',
    ],
    // These ESM-only packages (no CJS main / `"type":"module"`) are bundled
    // into our output so the CJS build resolves them correctly.
    noExternal: [
      'nanoid',
      'tokenlens',
      'media-chrome',
      'streamdown',
      '@streamdown/cjk',
      '@streamdown/code',
      '@streamdown/math',
      '@streamdown/mermaid',
    ],
    dts: true,
    sourcemap: true,
  },
]);
